### PR TITLE
fix(home page section one): fix responsiveness and translation

### LINKED ISSUE #7: HomePageSectionOne
this is gonna be taking care of by @iman-om 
both the hero section in home page + How it Works pages

### PR DESCRIPTION
**Pull request by iman-om**
Improve responsiveness, enhance translation functionality, and refine the layout for an enhanced user experience.

# Related Issue

- Resolve #7

### CODE REVIEW

**Review by Khalil-NOUI — COMMENTED** [review]
well done.

File: src/components/homepage/HowitWorks.jsx [hunk 1]
```diff
@@ -1,62 +1,71 @@
...
+            logo: t("Get started"),
             link: "/createEvent",
         },
     ];
 
     return (
-        <div className='mt-20 mx-auto text-center max-w-[1440px] px-6'>
-            <h2 className='text-zinc-900 text-4xl font-medium mb-20'>
-                How it Works
+        <div className='mt-20 mx-auto text-center max-w-6xl px-6'>
```
Comment (HachemBouhadede) [inline src/components/homepage/HowitWorks.jsx:43]: glad to see the feedback has been taken in consideration <3

**Review by HachemBouhadede — APPROVED** [review]
great work !
